### ISSUE TITLE
  'mc.cores' > 1 is not supported on Windows 

### ISSUE THREAD

**Issue by chagag** [myeomans/DTMtools#1]
When I run this on windows I get this error: 
'mc.cores' > 1 is not supported on Windows 

If you can allow mc.cores=1 this could run (perhaps by allowing a modification of that feature). 

Thanks!
Amit

**Comment by myeomans** [comment]
Thanks, Amit! Great point... I added mc.cores as an argument to the main function, which gets passed down to the mclapply calls. The default is mc.cores=1, which should work just fine on windows. Let me know if that solves it for you!

**Comment by chagag** [comment]
Thanks!
